import { tv } from "tailwind-variants";

export const NavbarStyle = tv({
  slots: {
    base: [
      "border",
      "border-primary-850/80",
      "w-full",
      "max-w-[95%]",
      "mx-auto",
      "rounded-2xl",
      "mt-2",
      "flex",
      "flex-col",
      "gap-0",
      "bg-primary-600/90",
      "fixed",
      "top-2",
      "left-0",
      "right-0",
      "z-40",
      "shadow-md",
    ],
    mainNavContainer: [
      "flex",
      "items-center",
      "justify-between",
      "gap-4",
      "px-[26px]",
      "lg:px-[6%]",
      "py-2",
      "lg:py-1",
    ],
    logoStyle: ["max-w-[119px]", "w-full"],
    wrapperButtons: ["flex", "items-center", "gap-4"],
    button: ["cursor-pointer", "px-4", "hidden", "msm:block"],
    simpleHeader: [
      "fixed",
      "left-0",
      "right-0",
      "top-0",
      "z-40",
      "bg-primary-600/95",
      "shadow-md",
    ],
    simpleContainer: [
      "mx-auto",
      "flex",
      "h-16",
      "w-full",
      "max-w-[1280px]",
      "items-center",
      "px-6",
      "md:px-10",
    ],
    sessionWrapper: ["hidden", "lg:block"],
    mobileWrapper: ["lg:hidden"],
  }
});
