#!/bin/bash
set -e

STAGE="$STAGE" 
AWS_REGION="$AWS_REGION"
SECRET_NAME="$SECRET_NAME"

CERT_FILE="/etc/ssl/cf/cert.pem"
KEY_FILE="/etc/ssl/cf/cert.key"
mkdir -p /etc/ssl/cf
mkdir -p /home/ec2-user/app/$STAGE

if [ "$STAGE" == "stg" ]; then
  mkdir -p /home/ec2-user/app/dev
fi

dnf update -y
dnf upgrade -y
dnf install -y --allowerasing postgresql17 nginx unzip curl wget jq

SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id $SECRET_NAME --region $AWS_REGION --query SecretString --output text)

echo "$SECRET_JSON" | jq -r '.CERTIFICATE' > $CERT_FILE
echo "$SECRET_JSON" | jq -r '.PRIVATE_KEY' > $KEY_FILE
STRAPI_URL=$(echo "$SECRET_JSON" | jq -r '.STRAPI_URL')
DEV_STRAPI_URL=$(echo "$SECRET_JSON" | jq -r '.DEV_STRAPI_URL')

if [ "$(cat $CERT_FILE)" == "null" ] || [ ! -s "$CERT_FILE" ]; then
  rm -f $CERT_FILE $KEY_FILE
  echo "SSL: Certificados no encontrados o inválidos. Continuando en modo HTTP."
fi

ENV_FILE="/home/ec2-user/app/$STAGE/.env"
echo "# Generated by CDK UserData" > $ENV_FILE 
echo "$SECRET_JSON" | jq -r 'to_entries | .[] | "\(.key)=\(.value)"' >> $ENV_FILE
chown ec2-user:ec2-user $ENV_FILE


if [ "$STAGE" == "stg" ]; then
  ENV_FILE_DEV="/home/ec2-user/app/dev/.env"
  
  echo "# Generated by CDK UserData - DEV" > "$ENV_FILE_DEV"
  
  echo "$SECRET_JSON" | jq -r "to_entries | .[] | 
    if .key == \"PORT\" then .value = \"1338\" 
    elif .key == \"STRAPI_URL\" then .value = \"$DEV_STRAPI_URL\" 
    else . end | \"\(.key)=\(.value)\"" >> "$ENV_FILE_DEV"
    
  chown ec2-user:ec2-user "$ENV_FILE_DEV"
fi

sudo -u ec2-user bash <<'EOF'
cd ~
curl -fsSL https://bun.sh/install | bash
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.4/install.sh | bash

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

nvm install --lts
npm install -g pm2

cat <<'EOT' >> ~/.bashrc
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
EOT
EOF

mkdir -p /etc/nginx/snippets

cat <<EOF > /etc/nginx/snippets/timeout.conf
proxy_connect_timeout 60s;
proxy_send_timeout 60s;
proxy_read_timeout 60s;
send_timeout 60s;
EOF

cat <<EOF > /etc/nginx/snippets/security.conf
add_header X-Content-Type-Options nosniff always;
add_header X-Frame-Options DENY always;
add_header X-XSS-Protection "1; mode=block" always;
add_header Referrer-Policy "no-referrer" always;
add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
EOF

cat <<EOF > /etc/nginx/snippets/proxy_headers.conf
proxy_set_header Host \$host;
proxy_set_header X-Real-IP \$remote_addr;
proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto \$scheme;
EOF

cat <<EOF > /etc/nginx/snippets/ssl_params.conf
ssl_protocols TLSv1.2 TLSv1.3;
ssl_ciphers 'ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384';
ssl_prefer_server_ciphers on;
ssl_session_cache shared:SSL:10m;
ssl_session_timeout 1h;
EOF

sed -i '/^    server {/,/^    }/d' /etc/nginx/nginx.conf

if [ -f "$CERT_FILE" ] && [ -f "$KEY_FILE" ]; then
  cat <<EOF > /etc/nginx/conf.d/main.conf
server {
  listen 80 default_server;
  server_name _;
  return 301 https://\$host\$request_uri;
}

server {
  listen 443 ssl http2;
  server_name $STRAPI_URL;
  
  ssl_certificate $CERT_FILE;
  ssl_certificate_key $KEY_FILE;
  
  include /etc/nginx/snippets/ssl_params.conf;
  include /etc/nginx/snippets/security.conf;
  include /etc/nginx/snippets/timeout.conf;

  location / {
    proxy_pass http://localhost:1337;
    include /etc/nginx/snippets/proxy_headers.conf;
    client_max_body_size 20M;
  }
}

$( [[ "$STAGE" == "stg" ]] && echo "
server {
  listen 443 ssl http2;
  server_name $DEV_STRAPI_URL;
  
  ssl_certificate $CERT_FILE;
  ssl_certificate_key $KEY_FILE;
  
  include /etc/nginx/snippets/ssl_params.conf;
  include /etc/nginx/snippets/security.conf;
  include /etc/nginx/snippets/timeout.conf;

  location / {
    proxy_pass http://localhost:1338;
    include /etc/nginx/snippets/proxy_headers.conf;
    client_max_body_size 20M;
  }
}" 
)
EOF
else
  cat <<EOF > /etc/nginx/conf.d/main.conf
server {
  listen 80 default_server;
  server_name _;
  
  include /etc/nginx/snippets/security.conf;
  include /etc/nginx/snippets/timeout.conf;

  location / {
    proxy_pass http://localhost:1337;
    include /etc/nginx/snippets/proxy_headers.conf;
    client_max_body_size 5M;
  }

  $( [[ "$STAGE" == "stg" ]] && echo "
  location /dev/ {
    proxy_pass http://localhost:1338;
    include /etc/nginx/snippets/proxy_headers.conf;
    client_max_body_size 5M;
  }" )
}
EOF
fi

rm -f /etc/nginx/conf.d/default.conf

nginx -t
sudo systemctl enable --now nginx
sudo systemctl restart nginx

echo "Change ownership of app folder"
sudo chown -R ec2-user:ec2-user /home/ec2-user/app
echo "Setup finished for stage $STAGE in region $AWS_REGION"